# Generated by Django 4.2.4 on 2023-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('studentname', models.CharField(max_length=50)),
                ('studentid', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
