# Generated by Django 4.2.4 on 2023-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentid', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'attendancedb',
            },
        ),
    ]
