# Generated by Django 4.2.4 on 2023-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0003_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
