# Generated by Django 4.2.4 on 2023-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0005_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentid', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='imagesForFacialRecognition')),
            ],
            options={
                'db_table': 'imagedetailsdb',
            },
        ),
    ]
