# Generated by Django 4.2.4 on 2023-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0006_imagedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetails',
            name='image',
            field=models.ImageField(default='', upload_to='imagesForFacialRecognition/'),
        ),
    ]
