# Generated by Django 4.2.4 on 2023-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0007_alter_imagedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetails',
            name='image',
            field=models.ImageField(upload_to='imagesForFacialRecognition/'),
        ),
    ]
