# Generated by Django 4.2.4 on 2023-11-02 20:35

from django.db import migrations, models
import tempfacetrace.models


class Migration(migrations.Migration):

    dependencies = [
        ('tempfacetrace', '0008_alter_imagedetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagedetails',
            name='image',
            field=models.ImageField(upload_to=tempfacetrace.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='imagedetails',
            name='studentid',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
